### ISSUE TITLE
Run CI on a Windows container

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis_core#180]
Try with something like
```
  ci-windows:
    name: >
      Run Windows-based checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp_vsn: [23.2]
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: gleam-lang/setup-erlang@v1.1.2
      with:
        otp-version: ${{matrix.otp_vsn}}
      id: install_erlang
    - run: wget https://s3.amazonaws.com/rebar3/rebar3 -OutFile rebar3
      shell: powershell
    - run: |
        & "${{steps.install_erlang.outputs.erlpath}}\bin\escript.exe" rebar3 dialyzer
    - run: |
        & "${{steps.install_erlang.outputs.erlpath}}\bin\escript.exe" rebar3 ct
    - run: |
        & "${{steps.install_erlang.outputs.erlpath}}\bin\escript.exe" rebar3 cover
    - run: |
        & "${{steps.install_erlang.outputs.erlpath}}\bin\escript.exe" rebar3 escriptize
    - run: |
        & "_build\default\bin\elvis_core"
```
in `ci.yml`.
